#!/bin/bash

# VLC ignores content-type header in case of m3u8, so URL should be set
# as the first parameter and then query string should be split on URL
# and rest of query string

if [ "$DOCUMENT_URI" == "/" ]; then
    DOCUMENT_URI="${QUERY_STRING%%&*}"
    QUERY_STRING="${QUERY_STRING#$DOCUMENT_URI}"
    QUERY_STRING="${QUERY_STRING#&}"
fi

# Stream URL query string
QS="${QUERY_STRING%%--*}"
# youtube-dl options
OPTIONS="${QUERY_STRING#${QS}}"
# Stream URL: strip trailing ampersand, leading slash, and protocol schema
URL="$DOCUMENT_URI${QS:+?$QS}"
URL=${URL%\&}
URL=${URL#/}
URL=${URL#http:/}
URL=${URL#https:/}

# Compose options from the query string replacing ampersand with space.
OPTIONS="${OPTIONS//\&/ }"

# Debug option.
if [ "${OPTIONS/--debug/}" != "$OPTIONS" ]; then
    debug=1
    OPTIONS="${OPTIONS/--debug/}"
    exec 2>&1
    echo "Content-Type: text/plain"
    set -x -v
fi


# Redirect standard error to standard output to get text output in response for some options.
echo "$OPTIONS" |
grep -qEe '(--list-)|(--dump-)|(--print-)|(--get-)|(--stderr)|(--help)' &&
STDERR="2>&1"
# Remove error option
OPTIONS="${OPTIONS/--stderr/}"
# Remove equal sign at the end of every option added by crazy yandex cloud
OPTIONS="${OPTIONS%=}"
OPTIONS="${OPTIONS//= /}"

echo "Content-Type: application/octet-stream"
echo
eval ${debug:+echo} youtube-dl $OPTIONS -o - "$URL" $STDERR
