name: main

on: [workflow_dispatch, push]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPO: youtube-dl-service
  PORT: 7000
  entry: 8000

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: build
        run: docker build -t $DOCKER_USERNAME/$DOCKER_REPO .
      - name: install
        run: pip install pytest-cov pytest-flake8 codecov
      - name: run
        run: docker run -d -e PORT=$PORT -p $entry:$PORT $DOCKER_USERNAME/$DOCKER_REPO
      - name: sleep
        run: sleep 4
      - name: test
        run: python -m pytest
      - name: deploy
        env:
          YOV_API_KEY: ${{ secrets.YOV_API_KEY }}
          YOV_IDENTITY: ${{ secrets.YOV_IDENTITY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          YOQ_API_KEY: ${{ secrets.YOQ_API_KEY }}
          YOQ_IDENTITY: ${{ secrets.YOQ_IDENTITY }}
          YOF_API_KEY: ${{ secrets.YOF_API_KEY }}
          YOF_IDENTITY: ${{ secrets.YOF_IDENTITY }}
          HEROKU: ${{ secrets.HEROKU }}
        run: ./deploy.sh
