name: main

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPO: youtube-dl-service
  PORT: 7000
  entry: 8000

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: build
        run: docker build -t $DOCKER_USERNAME/$DOCKER_REPO .
      - name: install
        run: pip install pytest-cov pytest-flake8 codecov
      - name: run
        run: docker run -d -e PORT=$PORT -p $entry:$PORT $DOCKER_USERNAME/$DOCKER_REPO
      - name: sleep
        run: sleep 4
      - name: test
        run: python -m pytest
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: deploy
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          HEROKU: ${{ secrets.HEROKU }}
        run: ./deploy.sh
