name: main

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        type: boolean
      youtube-dl:
        description: 'Youtube-dl update indicator'
        required: false

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPO: youtube-dl-service
  PORT: 80
  entry: 7000

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-python@v2
      - name: build
        run: docker build -t $DOCKER_USERNAME/$DOCKER_REPO .
      - uses: codecov/codecov-action@v3
      - name: install
        run: pip install pytest-cov pytest-flake8 versioningit
      - name: run
        run: docker run -d -e PORT=$PORT -p $entry:$PORT $DOCKER_USERNAME/$DOCKER_REPO
      - name: sleep
        run: sleep 4
      - name: test
        run: python -m pytest
      - name: Setup tmate session
        if: ${{ inputs.debug_enabled ||
                failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: deploy
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        if: ${{ startsWith(github.ref, 'refs/tags/') ||
                github.event.inputs.youtube-dl }}
        run: ./deploy.sh
